version: '3'
services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/src/go/app
      # Ignore the DB data, mount empty volume
      - /src/go/app/db
    ports:
      - "8080:8080"
  db:
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-root-pass
      - MYSQL_DATABASE=${VTSB_ADMIN_DB_NAME}
      - MYSQL_USER=${VTSB_ADMIN_DB_USER}
      - MYSQL_PASSWORD=${VTSB_ADMIN_DB_PASS}
    volumes:
      - ./db:/var/lib/mysql